name: Download OUI files and create the 'ouifiles' release
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4.1.1
      with:
        # ssh-key: ${{ secrets.REPO_SSH_KEY }}
        repository: rabuchaim/macvendorlookup
        sparse-checkout: .
        ref: main
    - name: Download OUI files from ieee.org website
      run: |
        mkdir files
        cd files 
        wget -O oui36.txt https://standards-oui.ieee.org/oui36/oui36.txt
        wget -O mam.txt https://standards-oui.ieee.org/oui28/mam.txt
        wget -O oui.txt https://standards-oui.ieee.org/oui/oui.txt
        DATA=$(TZ=America/Sao_Paulo date +'%d/%m/%Y às %H:%M:%S')
        ESCAPED_DATA=$(echo "${DATA}" | perl -pe 's/\//\\\//g')
        echo "TAG_DATA=$DATA" >> $GITHUB_ENV
        echo "TAG_ESCAPED_DATA=$ESCAPED_DATA" >> $GITHUB_ENV
    - name: Delete the old 'ouifiles' release
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd files
        gh release list
        gh release delete ouifiles
        gh release list
    - name: Create the new 'ouifiles' release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd files
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        gh release create ouifiles *.txt --title "UOI files from ${{ env.TAG_DATA_RELEASE }}" --verify-tag
permissions: write-all